# frozen_string_literal: true

# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv'
gem 'lineworks'
gem 'sinatra'

gem "rackup", "~> 2.1"

gem "activesupport", "~> 7.1"
